services:

    saludtech:
        build:
            context: .
            dockerfile: saludtech.Dockerfile
        # depends_on:
        #     - db
        environment:
            - PYTHONUNBUFFERED=1
        ports:
            - "5000:5000"

    # db:
    #     image: postgres:16
    #     environment:
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: postgres
    #         POSTGRES_DB: saludtech
    #     ports:
    #         - "5432:5432"
    #     healthcheck:
    #         test: ["CMD-SHELL", "pg_isready -U postgres -d saludtech"]
    #         interval: 2s
    #         timeout: 5s
    #         retries: 5
 
